package com.efi.printsmith.security;

public enum ApplicationCommandId implements CommandId {
	QuickAccess,
	AccountPicker,
	CashRegister,
	ChargeDefinitions,
	ChargePicker,
	ClockInOut,
	CopierDefinitions,
	EditCampaigns,
	EditContact,
	EditCustomer,
	EditEmployee,
	EditInvoice,
	EditJob,
	EditUser,
	EmployeeManager,
	EmployeePicker,
	EstimateHistory,
	ListUsers,
	NotePadEditor,
	PendingList,
	PressDefinitions,
	PriceListEditor,
	PriceListPicker,
	ScheduleManager,
	SecurityManager,
	StockDefinitions,
	StockPicker,
	SystemPreferences,
	TimeCardView,
	TimePeriodView,
	Tracker,
	Utilities
}
